USERS_DICTS = {
    2: ['u/Roger_Ebert', 'u/Dennis_Schwartz'],
    5: ['u/Roger_Moore', 'u/Jeffrey_M._Anderson', 'u/Roger_Ebert',
       'u/Brian_Orndorf', 'u/Dennis_Schwartz'],
    10: ['u/Roger_Moore', 'u/Jeffrey_M._Anderson', 'u/Roger_Ebert',
       'u/Rich_Cline', 'u/Brian_Orndorf', 'u/Frank_Swietek',
       'u/David_Nusair', 'u/Frederic_and_Mary_Ann_Brussat',
       'u/Dennis_Schwartz', 'u/James_Berardinelli'],
    20: ['u/Roger_Moore', 'u/MaryAnn_Johanson', 'u/Nell_Minow',
       'u/Jeffrey_M._Anderson', 'u/Roger_Ebert', 'u/Rich_Cline',
       'u/Brian_Orndorf', 'u/Frank_Swietek', 'u/Chris_Hewitt',
       'u/Peter_Bradshaw', 'u/David_Nusair', 'u/Harvey_S._Karten',
       'u/Emanuel_Levy', 'u/Frederic_and_Mary_Ann_Brussat',
       'u/Laura_Clifford', 'u/Ken_Hanke', 'u/Matt_Brunson',
       'u/Dennis_Schwartz', 'u/Eric_D._Snider', 'u/James_Berardinelli'],
    50: ['u/Nick_Schager', 'u/Roger_Moore', 'u/MaryAnn_Johanson',
       'u/Mark_Dujsik', 'u/Nell_Minow', 'u/Dustin_Putman',
       'u/Jeffrey_M._Anderson', 'u/Moira_MacDonald', 'u/Stephen_Whitty',
       'u/Jeff_Vice', 'u/Cole_Smithey', 'u/Roger_Ebert', 'u/Rich_Cline',
       'u/Matthew_Turner', 'u/Brian_Orndorf', 'u/Frank_Swietek',
       'u/Chris_Hewitt', 'u/Sara_Michelle_Fetters', 'u/Peter_Bradshaw',
       'u/David_Nusair', 'u/Robin_Clifford', 'u/Susan_Granger',
       'u/Robert_Roten', 'u/John_Beifuss', 'u/Michael_Dequina',
       'u/Harvey_S._Karten', 'u/Emanuel_Levy',
       'u/Frederic_and_Mary_Ann_Brussat', 'u/Laura_Clifford',
       'u/Richard_Roeper', 'u/Ty_Burr', 'u/Josh_Larsen', 'u/Peter_Rainer',
       'u/Mick_LaSalle', 'u/Tim_Brayton', 'u/Peter_Travers',
       'u/Ken_Hanke', 'u/Matt_Brunson', 'u/Dennis_Schwartz',
       'u/Gary_Thompson', 'u/Eric_D._Snider', 'u/Scott_Weinberg',
       'u/Steve_Rhodes', 'u/James_Kendrick', 'u/Felix_Vasquez_Jr.',
       'u/James_Berardinelli', 'u/Sean_P._Means', 'u/Mike_McGranaghan',
       'u/Owen_Gleiberman', 'u/Todd_Jorgenson'],
    80: ['u/Nick_Schager', 'u/Roger_Moore', 'u/MaryAnn_Johanson',
       'u/Mark_Dujsik', 'u/Nell_Minow', 'u/Dustin_Putman',
       'u/Jeffrey_M._Anderson', 'u/Kenneth_Turan', 'u/Moira_MacDonald',
       'u/Stephen_Whitty', 'u/Jeff_Vice', 'u/Wesley_Morris',
       'u/Cole_Smithey', 'u/Michael_Phillips', 'u/Matt_Pais',
       'u/Roger_Ebert', 'u/Rich_Cline', 'u/Matthew_Turner',
       'u/Walter_Chaw', 'u/Tom_Long', 'u/Brian_Orndorf', 'u/Jim_Judy',
       'u/Lou_Lumenick', 'u/Frank_Swietek', 'u/Chris_Hewitt',
       'u/Sara_Michelle_Fetters', 'u/Peter_Bradshaw', 'u/David_Nusair',
       'u/Fred_Topel', 'u/Robin_Clifford', 'u/A.O._Scott',
       'u/Susan_Granger', 'u/Robert_Roten', 'u/John_Beifuss',
       'u/Cynthia_Fuchs', 'u/Michael_Dequina', 'u/Peter_Canavese',
       'u/Kevin_Carr', 'u/Richard_Propes', 'u/Harvey_S._Karten',
       'u/Emanuel_Levy', 'u/Frederic_and_Mary_Ann_Brussat',
       'u/Claudia_Puig', 'u/Laura_Clifford', 'u/Richard_Roeper',
       'u/Kyle_Smith', 'u/Ty_Burr', 'u/Josh_Larsen', 'u/J._R._Jones',
       'u/Peter_Rainer', 'u/Mick_LaSalle', 'u/Peter_Howell',
       'u/Tim_Brayton', 'u/Peter_Travers', 'u/Josh_Bell', 'u/Ken_Hanke',
       'u/Matt_Brunson', 'u/Dennis_Schwartz', 'u/Stephanie_Zacharek',
       'u/Marjorie_Baumgarten', 'u/Gary_Thompson', 'u/Eric_D._Snider',
       'u/Scott_Weinberg', 'u/Steve_Rhodes', 'u/Pablo_Villaça',
       'u/Phil_Villarreal', 'u/Christopher_Null', 'u/James_Kendrick',
       'u/Felix_Vasquez_Jr.', 'u/Sean_Axmaker', 'u/Edward_Douglas',
       'u/James_Berardinelli', 'u/Luke_Y._Thompson', 'u/Sean_P._Means',
       'u/Linda_Cook', 'u/Mike_McGranaghan', 'u/Maitland_McDonagh',
       'u/Owen_Gleiberman', 'u/Todd_Jorgenson', 'u/Steven_Rea']
}
